name: Deploy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - dev

permissions:
  actions: read
  contents: read

jobs:
  debug:
    uses: ./.github/workflows/dev.yml
    secrets: inherit
  deploy:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Deploy Request Bundle to Gist
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: b7524906119fa250bc933cc9a08e939a
          gist_description: " iRingo: 🗺️ Maps β"
          file_path: dist/request.bundle.js
      - name: Deploy Response Bundle to Gist
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: b7524906119fa250bc933cc9a08e939a
          gist_description: " iRingo: 🗺️ Maps β"
          file_path: dist/response.bundle.js
      - name: Deploy Surge Module to Gist
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: b7524906119fa250bc933cc9a08e939a
          gist_description: " iRingo: 🗺️ Maps β"
          file_path: dist/iRingo.MapKit.dev.sgmodule
      - name: Deploy Loon Plugin to Gist
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: b7524906119fa250bc933cc9a08e939a
          gist_description: " iRingo: 🗺️ Maps β"
          file_path: dist/iRingo.MapKit.dev.plugin
      - name: Deploy Quantumult X Snippet to Gist
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: b7524906119fa250bc933cc9a08e939a
          gist_description: " iRingo: 🗺️ Maps β"
          file_path: dist/iRingo.MapKit.dev.snippet
      - name: Deploy Stash Override to Gist
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: b7524906119fa250bc933cc9a08e939a
          gist_description: " iRingo: 🗺️ Maps β"
          file_path: dist/iRingo.MapKit.dev.stoverride
