name: Workers Dev
on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy-dev-workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Install Node Dependencies
        uses: ./.github/actions/node-build
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.71.0"
